workflows:
  ios-build:
    name: iOS Build & Archive
    instance_type: mac_mini_m1
    environment:
      xcode: "16.1"
      vars:
        PROJECT_PATH: "Sources/MomentumOS/MomentumOS.xcodeproj"
        SCHEME: "MomentumOS"
        BUILD_CONFIGURATION: "Release"
        CODE_SIGN_STYLE: "automatic"
      groups:
        - apple_credentials  # Set this environment group in Codemagic UI with: TEAM_ID, APPLE_ID, APP_SPECIFIC_PASSWORD
        - code_signing       # Set this environment group in Codemagic UI with: CODE_SIGN_IDENTITY, PROVISIONING_PROFILE_NAME (if manual signing)

    scripts:
      - name: Checkout repository
        script: |
          set -e
          echo "Project root: $CM_BUILD_DIR"

      - name: Resolve Swift packages
        script: |
          set -e
          cd $CM_BUILD_DIR
          swift package resolve

      - name: Run unit tests (simulator)
        script: |
          set -e
          cd $CM_BUILD_DIR
          xcodebuild -project "$PROJECT_PATH" -scheme "$SCHEME" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0' test 2>&1 | tee xcode_build.log || exit ${PIPESTATUS[0]}

      - name: Create Xcode archive
        script: |
          set -e
          cd $CM_BUILD_DIR
          ARCHIVE_PATH="$CM_BUILD_DIR/build/$SCHEME.xcarchive"
          mkdir -p "$(dirname "$ARCHIVE_PATH")"
          xcodebuild -project "$PROJECT_PATH" -scheme "$SCHEME" -configuration "$BUILD_CONFIGURATION" -archivePath "$ARCHIVE_PATH" archive \
            CODE_SIGN_STYLE="$CODE_SIGN_STYLE" \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            | tee -a xcode_build.log || exit ${PIPESTATUS[0]}

      - name: Export IPA
        script: |
          set -e
          cd $CM_BUILD_DIR
          EXPORT_PATH="$CM_BUILD_DIR/build/export"
          mkdir -p "$EXPORT_PATH"
          ARCHIVE_PATH="$CM_BUILD_DIR/build/$SCHEME.xcarchive"
          
          # Create ExportOptions.plist for app-store distribution
          cat > /tmp/ExportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>uploadBitcode</key>
            <false/>
            <key>compileBitcode</key>
            <true/>
            <key>teamID</key>
            <string>$TEAM_ID</string>
            <key>signingStyle</key>
            <string>automatic</string>
          </dict>
          </plist>
          EOF
          
          xcodebuild -exportArchive -archivePath "$ARCHIVE_PATH" -exportOptionsPlist /tmp/ExportOptions.plist -exportPath "$EXPORT_PATH" \
            | tee -a xcode_build.log || exit ${PIPESTATUS[0]}

      - name: Publish to App Store Connect (optional)
        script: |
          set -e
          if [ -n "$APPLE_ID" ] && [ -n "$APP_SPECIFIC_PASSWORD" ]; then
            IPA=$(find $CM_BUILD_DIR/build/export -name "*.ipa" | head -n1)
            if [ -f "$IPA" ]; then
              echo "Uploading $IPA to App Store Connect..."
              xcrun altool --upload-app -f "$IPA" -u "$APPLE_ID" -p "$APP_SPECIFIC_PASSWORD" --type ios
            else
              echo "No IPA found to upload."
              exit 1
            fi
          else
            echo "APPLE_ID or APP_SPECIFIC_PASSWORD not set — skipping App Store upload."
            echo "Set these in Codemagic UI → Environment groups → apple_credentials"
          fi

    artifacts:
      - build/export/*.ipa
      - build/*.xcarchive
      - xcode_build.log

  backend-tests:
    name: Backend tests (Node)
    instance_type: linux
    environment:
      node: "18.20.0"
    
    scripts:
      - name: Install dependencies
        script: |
          set -e
          cd $CM_BUILD_DIR/backend
          npm ci

      - name: Run backend tests
        script: |
          set -e
          cd $CM_BUILD_DIR/backend
          npm test || echo "Tests completed (check logs for details)"

    artifacts:
      - backend/test-reports/**/*.xml
