workflows:
  ios-build:
    name: iOS Build & Archive
    # macOS runner (choose runner depending on plan; mac_mini_m1 or mac_mini_m2 are common)
    instance_type: mac_mini_m1

    # Xcode version to use (adjust to the version you need)
    environment:
      xcode: "15.0"
      # Useful variables you can override in Codemagic UI
      vars:
        PROJECT_PATH: "Sources/MomentumOS/MomentumOS.xcodeproj"   # or the .xcworkspace path if you have one
        SCHEME: "MomentumOS"
        BUILD_CONFIGURATION: "Release"
        TEAM_ID: ""
        APP_IDENTIFIER: ""
        # Code signing variables (see notes below)
        CODE_SIGN_STYLE: "manual" # or "automatic"
        CODE_SIGN_IDENTITY: ""
        PROVISIONING_PROFILE_NAME: ""
        # App Store Connect publishing (optional)
        APPLE_ID: ""
        APP_SPECIFIC_PASSWORD: ""

    scripts:
      - name: Checkout repository
        script: |
          set -e
          echo "Project root: $CM_BUILD_DIR"
      - name: Resolve Swift packages
        script: |
          set -e
          cd $CM_BUILD_DIR
          # If you use an Xcode workspace, use that. Otherwise resolve SPM at repo root.
          swift package resolve
      - name: Run unit tests (simulator)
        script: |
          set -e
          cd $CM_BUILD_DIR
          # Example test command - adjust destination/simulator OS to match your test targets
          xcodebuild -project "$PROJECT_PATH" -scheme "$SCHEME" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.0' test | xcpretty || exit ${PIPESTATUS[0]}
      - name: Create Xcode archive
        script: |
          set -e
          cd $CM_BUILD_DIR
          ARCHIVE_PATH="$CM_BUILD_DIR/build/$SCHEME.xcarchive"
          mkdir -p "$(dirname "$ARCHIVE_PATH")"
          xcodebuild -project "$PROJECT_PATH" -scheme "$SCHEME" -configuration "$BUILD_CONFIGURATION" -archivePath "$ARCHIVE_PATH" archive CODE_SIGN_STYLE="$CODE_SIGN_STYLE" DEVELOPMENT_TEAM="$TEAM_ID" CODE_SIGN_IDENTITY="$CODE_SIGN_IDENTITY" PROVISIONING_PROFILE_SPECIFIER="$PROVISIONING_PROFILE_NAME" | xcpretty || exit ${PIPESTATUS[0]}
      - name: Export IPA
        script: |
          set -e
          cd $CM_BUILD_DIR
          EXPORT_PATH="$CM_BUILD_DIR/build/export"
          mkdir -p "$EXPORT_PATH"
          # Use an ExportOptions.plist in the repo or generate one dynamically. Example uses AdHoc/app-store; change method as needed.
          EXPORT_OPTIONS_PLIST="$CM_BUILD_DIR/ci/ExportOptions.plist"
          if [ ! -f "$EXPORT_OPTIONS_PLIST" ]; then
            cat > "$EXPORT_OPTIONS_PLIST" <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>uploadBitcode</key>
            <false/>
            <key>compileBitcode</key>
            <true/>
            <key>teamID</key>
            <string>${TEAM_ID}</string>
          </dict>
          </plist>
          EOF
          fi
          xcodebuild -exportArchive -archivePath "$ARCHIVE_PATH" -exportOptionsPlist "$EXPORT_OPTIONS_PLIST" -exportPath "$EXPORT_PATH" | xcpretty || exit ${PIPESTATUS[0]}
      - name: Publish to App Store Connect (optional)
        script: |
          set -e
          if [ -n "$APPLE_ID" ] && [ -n "$APP_SPECIFIC_PASSWORD" ]; then
            IPA=$(ls $CM_BUILD_DIR/build/export/*.ipa | head -n1)
            if [ -f "$IPA" ]; then
              echo "Uploading $IPA to App Store Connect..."
              xcrun altool --upload-app -f "$IPA" -u "$APPLE_ID" -p "$APP_SPECIFIC_PASSWORD" --type ios
            else
              echo "No IPA found to upload."
            fi
          else
            echo "APPLE_ID or APP_SPECIFIC_PASSWORD not set — skipping upload."
          fi

    artifacts:
      - build/export/*.ipa
      - build/*.xcarchive

  backend-tests:
    name: Backend tests (Node)
    instance_type: standard
    environment:
      node: "18.20.0"   # change to supported version
    scripts:
      - name: Install & test backend
        script: |
          set -e
          cd $CM_BUILD_DIR/backend
          npm ci
          npm test || true   # adjust to your test command; `true` keeps pipeline from failing if you want to inspect
    artifacts:
      - backend/test-reports/**/*.xml
